### =========================================================================
### tigeR.data metadata
### -------------------------------------------------------------------------
###


meta <- data.frame(
  Title = c(paste0("RNA-Sequencing and clinical data for GBM_PRJNA482620 ",
                   "samples from BioProject"),
            paste0("RNA-Sequencing and clinical data for HNSC_GSE93157 ",
                   "samples from GEO"),
            paste0("RNA-Sequencing and clinical data for LGG_E_MTAB_6270 ",
                   "samples from EMBL-EBI"),
            paste0("RNA-Sequencing and clinical data for MEL_GSE78220 ",
                   "samples from GEO"),
            paste0("RNA-Sequencing and clinical data for MEL_GSE91061 ",
                   "samples from GEO"),
            paste0("RNA-Sequencing and clinical data for MEL_GSE93157 ",
                   "samples from GEO"),
            paste0("RNA-Sequencing and clinical data for MEL_GSE96619 ",
                   "samples from GEO"),
            paste0("RNA-Sequencing and clinical data for MEL_GSE100797 ",
                   "samples from GEO"),
            paste0("RNA-Sequencing and clinical data for MEL_GSE106128 ",
                   "samples from GEO"),
            paste0("RNA-Sequencing and clinical data for MEL_GSE115821 ",
                   "samples from GEO"),
            paste0("RNA-Sequencing and clinical data for MEL_GSE145996 ",
                   "samples from GEO"),
            paste0("RNA-Sequencing and clinical data for MEL_Nathanson_2017 ",
                   "samples from online resource"),
            paste0("RNA-Sequencing and clinical data for MEL_phs000452 ",
                   "samples from dbGaP"),
            paste0("RNA-Sequencing and clinical data for MEL_PRJEB23709 ",
                   "samples from BioProject"),
            paste0("RNA-Sequencing and clinical data for nonsqNSCLC_GSE93157 ",
                   "samples from GEO"),
            paste0("RNA-Sequencing and clinical data for NSCLC_GSE126044 ",
                   "samples from GEO"),
            paste0("RNA-Sequencing and clinical data for NSCLC_GSE135222 ",
                   "samples GEO"),
            paste0("RNA-Sequencing and clinical data for RCC_Braun_2020 ",
                   "samples from assay https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7499153/"),
            paste0("RNA-Sequencing and clinical data for RCC_GSE67501 ",
                   "samples from GEO"),
            paste0("RNA-Sequencing and clinical data for STAD_PRJEB25780 ",
                   "samples from BioProject")),

  Description = c(paste0("An SummarizedExperiment object ",
                         "contains expression matrix(FPKM) and clinical information of ",
                         "Glioblastoma patients in PRJNA482620 data set. "),
                  paste0("An SummarizedExperiment object ",
                         "contains expression matrix(FPKM) and clinical information of ",
                         "Head and Neck Squamous patients in GSE93157 data set. "),
                  paste0("An SummarizedExperiment object ",
                         "contains expression matrix(FPKM) and clinical information of ",
                         "Brain Lower Grade Glioma patients in E-MTAB-6270 data set. "),
                  paste0("An SummarizedExperiment object ",
                         "contains expression matrix(FPKM) and clinical information of ",
                         "Melanoma patients in GSE78220 data set. "),
                  paste0("An SummarizedExperiment object ",
                         "contains expression matrix(FPKM) and clinical information of ",
                         "Melanoma patients in GSE91061 data set. "),
                  paste0("An SummarizedExperiment object ",
                         "contains expression matrix(FPKM) and clinical information of ",
                         "Melanoma patients in GSE93157 data set. "),
                  paste0("An SummarizedExperiment object ",
                         "contains expression matrix(FPKM) and clinical information of ",
                         "Melanoma patients in GSE96619 data set. "),
                  paste0("An SummarizedExperiment object ",
                         "contains expression matrix(FPKM) and clinical information of ",
                         "Melanoma patients in GSE100797 data set. "),
                  paste0("An SummarizedExperiment object ",
                         "contains expression matrix(FPKM) and clinical information of ",
                         "Melanoma patients in GSE106128 data set. "),
                  paste0("An SummarizedExperiment object ",
                         "contains expression matrix(FPKM) and clinical information of ",
                         "Melanoma patients in GSE115821 data set. "),
                  paste0("An SummarizedExperiment object ",
                         "contains expression matrix(FPKM) and clinical information of ",
                         "Melanoma patients in GSE145996 data set. "),
                  paste0("An SummarizedExperiment object ",
                         "contains expression matrix(FPKM) and clinical information of ",
                         "Melanoma patients in Nathanson_2017 data set. "),
                  paste0("An SummarizedExperiment object ",
                         "contains expression matrix(FPKM) and clinical information of ",
                         "Melanoma patients in phs000452 data set. "),
                  paste0("An SummarizedExperiment object ",
                         "contains expression matrix(FPKM) and clinical information of ",
                         "Melanoma patients in PRJEB23709 data set. "),
                  paste0("An SummarizedExperiment object ",
                         "contains expression matrix(FPKM) and clinical information of ",
                         "Non-small cell lung cancer patients in GSE93157 data set. "),
                  paste0("An SummarizedExperiment object ",
                         "contains expression matrix(FPKM) and clinical information of ",
                         "Non-small cell lung cancer patients in GSE126044 data set. "),
                  paste0("An SummarizedExperiment object ",
                         "contains expression matrix(FPKM) and clinical information of ",
                         "Non-small cell lung cancer patients in GSE135222 data set. "),
                  paste0("An SummarizedExperiment object ",
                         "contains expression matrix(FPKM) and clinical information of ",
                         "Renal cell carcinoma patients in Braun_2020 data set. "),
                  paste0("An SummarizedExperiment object ",
                         "contains expression matrix(FPKM) and clinical information of ",
                         "Renal cell carcinoma patients in GSE67501 data set. "),
                  paste0("An SummarizedExperiment object ",
                         "contains expression matrix(FPKM) and clinical information of ",
                         "Stomach adenocarcinoma patients in PRJEB25780 data set. ")),
  BiocVersion = rep(3.16,20),
  Genome = "hg19",
  SourceType = c("FASTQ","tar.gz","TXT","XLS/XLSX","tar.gz","tar.gz","XLS/XLSX","tar.gz",
                 "tar.gz","tar.gz","tar.gz","tar.gz","BAM","FASTQ","tar.gz","tar.gz",
                 "tar.gz","XLS/XLSX","tar.gz","FASTQ"),
  SourceUrl = c("https://www.ncbi.nlm.nih.gov/bioproject/?term=PRJNA482620",
                "https://www.ncbi.nlm.nih.gov/bioproject/?term=GSE93157",
                "https://www.ebi.ac.uk/biostudies/arrayexpress/studies/E-MTAB-6270?accession=E-MTAB-6270",
                "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE78220",
                "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE91061",
                "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE93157",
                "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE96619",
                "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE100797",
                "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE106128",
                "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE115821",
                "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE145996",
                "http://www.hammerlab.org/melanoma-reanalysis/",
                "https://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/study.cgi?study_id=phs000452.v3.p1",
                "https://www.ncbi.nlm.nih.gov/bioproject/?term=PRJEB23709",
                "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE93157",
                "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE126044",
                "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE135222",
                "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7499153/",
                "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE67501",
                "https://www.ncbi.nlm.nih.gov/bioproject/?term=PRJNA482620"),
  SourceVersion = c("Feb 08 2020","May 15 2017","Apr 03 2018","Mar 18 2016",
                    "Jan 23 2018","May 15 2017","May 09 2017","Dec 04 2017",
                    "Oct 25 2017","Aug 20 2018","Aug 07 2020","Dec 08 2016",
                    "Mar 02 2020","Feb 04 2019","May 15 2017","Feb 03 2020",
                    "Aug 02 2019","May 29 2020","Aug 04 2016","Jul 24 2018"),
  Species = "Homo sapiens",
  TaxonomyId = 9606,
  Coordinate_1_based = NA,
  DataProvider = c("BioProject",
                   "GEO",
                   "EMBL-EBI",
                   rep("GEO",8),
                   "oline resource",
                   "dbGaP","BioProject",
                   rep("GEO",3),
                   "oline resource",
                   "GEO",
                   "BioProject"),
  Maintainer = "<yihaochen224@gmail.com>",
  RDataClass = "SummarizedExperiment",
  DispatchClass = c(rep("Rda",20)),
  RDataPath = c(paste0("tigeR.data/GSE62944_GSM1536837_TCGA_20.Illumina.",
                       "tumor_Rsubread_FeatureCounts.ExpressionSet.Rda"),
                "tigeR.data/GSE62944_GSM1536837_TCGA_24.tumor_Rsubread_FeatureCounts.SE.Rda",
                "tigeR.data/GSE62944_GSM1697009_TCGA_24.normal_Rsubread_FeatureCounts.SE.Rda",
                "tigeR.data/GSE62944_GSM1536837_TCGA_24.tumor_Rsubread_FeatureCounts.SE.V2.Rda",
                "tigeR.data/GSE62944_GSM1697009_TCGA_24.normal_Rsubread_FeatureCounts.SE.V2.Rda"),
  Tags = ""
)

write.csv(meta, file="inst/extdata/metadata.csv", row.names=FALSE)
